### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by stolen-programmer** [WangHoi/kwui-rs#3]
![image](https://github.com/WangHoi/kwui-rs/assets/23734345/03eb6ba4-5ced-47f5-92f1-add2a6a6d43f)
![image](https://github.com/WangHoi/kwui-rs/assets/23734345/59a812b4-853a-4695-80f2-29079173c481)

**Comment by WangHoi** [comment]
我试了下，确实有问题，崩溃在abseil-cpp里加载时区文件里。
您是用的VS2019吗，预编译的kwui库是用的VS2022。

等我周末有空调查修复下。

**Comment by WangHoi** [comment]
您安装VS2022即可解决问题。

abseil-cpp 时区相关的初始化会加锁，触发崩溃。

根本原因是这里：
[microsoft STL Changelog](https://github.com/microsoft/STL/wiki/Changelog)

VS2022 STL 搞了骚操作，把 std::mutex 的构造函数搞成了 constexpr，ABI不兼容，导致崩溃了。

**Comment by stolen-programmer** [comment]
我用的就是22  虽然也有19

**Comment by stolen-programmer** [comment]
![image](https://github.com/WangHoi/kwui-rs/assets/23734345/a3b47686-b38d-45ed-b9de-8991803b41f3)

**Comment by WangHoi** [comment]
抱歉，麻烦您调试时，加载下这个压缩包里的kwui.pdb，看下崩溃时c++里的堆栈
https://github.com/WangHoi/kwui-binaries/releases/download/0.2.1/kwui-binaries-6021cc735774099f98fc-x86_64-pc-windows-msvc.tar.gz

**Comment by stolen-programmer** [comment]
你无法复现吗  我使用cli创建项目  通过cargo run 跑  跑不起来 然后rustrover 调试 报找不到kwui.dll 我从build目录随便找了个kwui.dll 然后就崩了 看起来是空指针

**Comment by stolen-programmer** [comment]
![image](https://github.com/WangHoi/kwui-rs/assets/23734345/4a9c9130-1680-46bf-87e3-761d437c017f)

**Comment by WangHoi** [comment]
> 你无法复现吗 我使用cli创建项目 通过cargo run 跑 跑不起来 然后rustrover 调试 报找不到kwui.dll 我从build目录随便找了个kwui.dll 然后就崩了 看起来是空指针

VS2019能复现，是上述的std::mutex ABI的问题，安装VS2022 17.10.3后正常了。
您试下cargo clean后重新编译。

启动时找不到dll，Rust Rover可能是需要手动设置下启动时的 dll 搜索路径，用 cargo run 是可以的。

实在不行可以把cpp部分也从源码编译：

1. 检出源码
```bash
git clone --recurse-submodules https://github.com/WangHoi/kwui
```
2. 修改您的项目的 Cargo.toml，指向源码
```toml
[patch.crates-io]
kwui = { path = "{cloned_kwui_dir}" }
kwui-sys = { path = "{cloned_kwui_dir}/kwui-sys" }
kwui-cli = { path = "{cloned_kwui_dir}/kwui-cli" }
```

**Comment by stolen-programmer** [comment]
![image](https://github.com/WangHoi/kwui-rs/assets/23734345/66ecc86e-baab-4099-b5ce-f6fb6f56af1e)
非常遗憾  检出的源码没有kwui-sys kwui-cli 甚至没有Cargo.toml

**Comment by WangHoi** [comment]
抱歉，是这个库：
git clone --recurse-submodules https://github.com/WangHoi/kwui-rs

**Comment by WangHoi** [comment]
kwui 依赖最新的 VCRedist，试下更新下VCRedist:
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
安装 “Latest Microsoft Visual C++ Redistributable Version” X64和X86版本

抱歉，下个版本的kwui-rs用VS2019来构建了。

> Fixed mutex’s constructor to be constexpr.
> Note: Programs that aren’t following the documented restrictions on binary compatibility may encounter null dereferences in  mutex machinery. You must follow this rule:
> When you mix binaries built by different supported versions of the toolset, the Redistributable version must be at least as new as the latest toolset used by any app component.
> 
> Solve the problem based on Karel Van de Rostyne’s comment:
> The solution for this problem is:
> Download the latest Microsoft Visual C++ Redistributables and install them on the machine that gives the problem.

**Comment by WangHoi** [comment]
![Bb8e3f384ce234079a89c84b1a9613275638526776656789155_20240530-165424-image](https://github.com/WangHoi/kwui-rs/assets/374280/95964c4a-3472-47a8-9d12-b25f9f4c3844)

**Comment by stolen-programmer** [comment]
![image](https://github.com/WangHoi/kwui-rs/assets/23734345/2e2cf919-22c2-4828-9081-70d60c0a102b)
我使用 vs2022 x64命令提示符 很遗憾 无法编译  另外 vcredist我都有

**Comment by stolen-programmer** [comment]
![image](https://github.com/WangHoi/kwui-rs/assets/23734345/ba204168-aced-475b-b1a7-83969cfe0879)
靠  内部编译器错误

**Comment by stolen-programmer** [comment]
我在尝试编译  已经有几次内部编译器错误  每次错误的地方不同  蓝屏三次  都是watch dog timeout  win10 酷睿14代i9 64g内存   我今年在编译上蓝屏已经超过20次

**Comment by stolen-programmer** [comment]
我几乎已经编译完成了
在最后的kwui.dll  每次都是内部错误  

直到卡了5秒  然后蓝屏

**Comment by stolen-programmer** [comment]
![image](https://github.com/WangHoi/kwui-rs/assets/23734345/51c75531-c9d7-457f-a737-f470175795fa)
痛定思痛 我把自动超频给关了   最高睿频4500MHz  然后 OK了
